export const BooksData = [
  //  Fiction Books
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
    price: 12.99,
    rating: 4.6,
    library: "LibraSphere",
    status: "Available",
    description:
      "A timeless story of wealth, love, and tragedy set in the roaring twenties. The Great Gatsby explores the American Dream in a world of decadence and illusion.",
  },
  {
    id: 2,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
    price: 10.99,
    rating: 4.7,
    library: "LibraSphere",
    status: "Available",
    description:
      "A witty and romantic exploration of manners and relationships. Elizabeth Bennet navigates love, class, and pride in Georgian England.",
  },
  {
    id: 3,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
    price: 11.49,
    rating: 4.9,
    library: "LibraSphere",
    status: "Available",
    description:
      "A classic novel addressing racial injustice and moral growth through the eyes of a young girl in the Depression-era South.",
  },
  {
    id: 4,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/id/8231853-L.jpg",
    price: 9.99,
    rating: 4.1,
    library: "LibraSphere",
    status: "Available",
    description:
      "A coming-of-age story following Holden Caulfield as he wanders through New York City, questioning the authenticity of the adult world.",
  },
  {
    id: 5,
    title: "Little Women",
    author: "Louisa May Alcott",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/id/5541062-L.jpg",
    price: 13.5,
    rating: 4.8,
    library: "LibraSphere",
    status: "Available",
    description:
      "A heartfelt tale of four sisters navigating love, ambition, and family in Civil War–era New England.",
  },
  {
    id: 6,
    title: "1984",
    author: "George Orwell",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
    price: 10.75,
    rating: 4.9,
    library: "LibraSphere",
    status: "Available",
    description:
      "A chilling vision of a totalitarian future where Big Brother watches all. A powerful warning against the dangers of absolute power.",
  },

  //  Non-Fiction Books
  {
    id: 7,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/id/8371361-L.jpg",
    price: 15.99,
    rating: 4.8,
    library: "LibraSphere",
    status: "Available",
    description:
      "An exploration of human evolution, tracing our species’ journey from primitive tribes to modern civilizations.",
  },
  {
    id: 8,
    title: "Educated",
    author: "Tara Westover",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/id/9258876-L.jpg",
    price: 13.99,
    rating: 4.7,
    library: "LibraSphere",
    status: "Available",
    description:
      "A memoir of a young woman who grows up in a survivalist family and pursues education against all odds, reshaping her destiny.",
  },
  {
    id: 9,
    title: "Becoming",
    author: "Michelle Obama",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/id/9258622-L.jpg",
    price: 16.5,
    rating: 4.9,
    library: "LibraSphere",
    status: "Available",
    description:
      "The deeply personal memoir of former First Lady Michelle Obama, chronicling her journey from Chicago to the White House.",
  },
  {
    id: 10,
    title: "The Power of Habit",
    author: "Charles Duhigg",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/id/8371657-L.jpg",
    price: 12.0,
    rating: 4.6,
    library: "LibraSphere",
    status: "Available",
    description:
      "A compelling look at how habits work and how they can be transformed to improve our personal and professional lives.",
  },
  {
    id: 11,
    title: "Atomic Habits",
    author: "James Clear",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/id/9258756-L.jpg",
    price: 14.0,
    rating: 4.9,
    library: "LibraSphere",
    status: "Available",
    description:
      "A powerful guide to building good habits and breaking bad ones through small, consistent changes that compound over time.",
  },
  {
    id: 12,
    title: "Man’s Search for Meaning",
    author: "Viktor E. Frankl",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/id/8234236-L.jpg",
    price: 10.49,
    rating: 4.8,
    library: "LibraSphere",
    status: "Available",
    description:
      "A profound account of survival, purpose, and hope from a psychiatrist who endured life in Nazi concentration camps.",
  },

  //  Sci-Fi Books
  {
    id: 13,
    title: "Dune",
    author: "Frank Herbert",
    category: "Sci-Fi",
    image: "https://covers.openlibrary.org/b/id/8101354-L.jpg",
    price: 14.99,
    rating: 4.7,
    library: "LibraSphere",
    status: "Available",
    description:
      "A science fiction epic set on the desert planet Arrakis, exploring politics, power, and destiny in a futuristic universe.",
  },
  {
    id: 14,
    title: "Ender's Game",
    author: "Orson Scott Card",
    category: "Sci-Fi",
    image: "https://covers.openlibrary.org/b/id/8235081-L.jpg",
    price: 11.99,
    rating: 4.8,
    library: "LibraSphere",
    status: "Available",
    description:
      "A young genius is trained through battle simulations to save humanity from alien invasion in this thrilling sci-fi classic.",
  },
  {
    id: 15,
    title: "Neuromancer",
    author: "William Gibson",
    category: "Sci-Fi",
    image: "https://covers.openlibrary.org/b/id/8225631-L.jpg",
    price: 12.49,
    rating: 4.5,
    library: "LibraSphere",
    status: "Available",
    description:
      "The novel that coined ‘cyberspace’ — a gritty, cyberpunk thriller that defined the digital age before it arrived.",
  },
  {
    id: 16,
    title: "The Martian",
    author: "Andy Weir",
    category: "Sci-Fi",
    image: "https://covers.openlibrary.org/b/id/8372256-L.jpg",
    price: 13.5,
    rating: 4.9,
    library: "LibraSphere",
    status: "Available",
    description:
      "A gripping story of survival as an astronaut stranded on Mars uses science and wit to find his way home.",
  },
  {
    id: 17,
    title: "Ready Player One",
    author: "Ernest Cline",
    category: "Sci-Fi",
    image: "https://covers.openlibrary.org/b/id/8371333-L.jpg",
    price: 13.99,
    rating: 4.6,
    library: "LibraSphere",
    status: "Available",
    description:
      "A high-energy adventure set in a virtual reality world where a young gamer competes to uncover the ultimate Easter egg.",
  },
  {
    id: 18,
    title: "Project Hail Mary",
    author: "Andy Weir",
    category: "Sci-Fi",
    image: "https://covers.openlibrary.org/b/id/11087339-L.jpg",
    price: 15.25,
    rating: 4.9,
    library: "LibraSphere",
    status: "Available",
    description:
      "A lone astronaut must save humanity from extinction in this scientifically rich and emotionally charged space odyssey.",
  },
];

export default BooksData;
